hooks / useHover
Byndyusoft/ui pull request #51
Opened 2022-11-28 11:53 UTC by Max-Tetslav

2022-12-07 08:43 UTC, sadcitizen requested changes

2022-12-07 08:43 UTC, sadcitizen commented on hooks/use-hover/src/useHover.ts
> +    return {
Давай лучше будем вешать событие через `ref`

2023-02-03 07:51 UTC, sadcitizen approved these changes

2023-02-03 08:03 UTC, mltsk approved these changes

2023-02-03 08:10 UTC, merged