Fix/build
Byndyusoft/ui pull request #69
Opened 2024-01-25 09:55 UTC by mltsk

2024-01-29 10:21 UTC, sadcitizen requested changes

2024-01-29 10:21 UTC, sadcitizen commented on package.json
> +    "@types/estree": "^1.0.5",
Для чего нужны эти тип?

2024-01-29 15:04 UTC, mltsk commented on package.json
> +    "@types/estree": "^1.0.5",
Сейчас без этих типов появляются следующие ошибки при сборки:
![Screenshot 2024-01-29 at 17 57 37](https://github.com/Byndyusoft/ui/assets/51035551/9dbc65a6-14c6-4044-9ae3-c5830e88c365)

Как я понял проблема в том, что какой-то пакет ставит старую версию @types/estree. Eslint находит @types/estree, но тк версия старая, то не находит нужные типы

2024-02-08 07:36 UTC, sadcitizen approved these changes

2024-02-08 07:36 UTC, merged