Feature/use array
Byndyusoft/ui pull request #70
Opened 2024-01-31 10:25 UTC by mltsk

2024-01-31 10:44 UTC, ancientbag commented on hooks/use-array/src/useArray.ts
> +export default function useArray<T>(initialValue: T[]): {
Я бы эти типы унес в интерфейс IUseArray

2024-01-31 10:50 UTC, ancientbag commented on hooks/use-array/src/useArray.ts
> +        [list]
Здесь можно заменить зависимость list на setList и через пропсы setList'а инкрементировать. То же самое для подобных функций

2024-02-01 09:26 UTC, sadcitizen requested changes

2024-02-08 06:35 UTC, sadcitizen approved these changes

2024-02-08 06:36 UTC, merged