update reset input styles
Byndyusoft/ui pull request #71
Opened 2024-01-31 12:38 UTC by SmorodinVik

2024-01-31 12:52 UTC, ancientbag commented
Отступы не скидываем?

2024-01-31 13:15 UTC, SmorodinVik commented
да, паддинг можно скинуть

2024-01-31 13:16 UTC, SmorodinVik commented
> Отступы не скидываем?

да, можно добавить

2024-02-08 07:37 UTC, sadcitizen requested changes

2024-02-08 07:37 UTC, sadcitizen commented on styles/reset-css/input.css
> +    padding: 0;
Давай пока уберём сброс отступов

2024-02-08 08:27 UTC, sadcitizen approved these changes

2024-02-08 08:28 UTC, merged