feat(reset-css): add sandbox page
Byndyusoft/ui pull request #81
Opened 2024-03-18 17:14 UTC by Oustinger

**!Attention!** при данной реализации sandbox'а, пакет reset-css применяется ко всем историям в storybook

Если устроит такой вариант, можно из него сделать страницу mdx для доки библиотеки

2024-04-11 03:34 UTC, sadcitizen requested changes

2024-04-11 03:34 UTC, sadcitizen commented on styles/reset-css/__stories__/ResetCss.stories.tsx
> +        <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '1rem' }}>
У тебя же есть файл со стилями, зачем тут надо было делать их инлайновыми?

2024-04-11 03:34 UTC, sadcitizen commented on styles/reset-css/__stories__/ResetCss.stories.tsx
> +                <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
И тут тоже инлайновые стили.

2024-04-11 12:21 UTC, Oustinger commented on styles/reset-css/__stories__/ResetCss.stories.tsx
> +        <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '1rem' }}>
Из-за использования iframe не получается адекватно подключить стили к контенту внутри iframe. Я не нашёл нормального способа. Поэтому так
* Вообще, подключить можно, но тогда подключатся сразу все стили из <head>, включая и пакет reset-css, а этого не нужно

2024-04-11 12:21 UTC, Oustinger commented on styles/reset-css/__stories__/ResetCss.stories.tsx
> +                <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
В этом месте избавился от инлайн стилей

2024-04-18 03:57 UTC, sadcitizen approved these changes

2024-04-18 03:58 UTC, merged